### 根据id查询唯一预定订单
POST http://localhost:8081/ordering/selectOne
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
    "orderCode": 3
}

### 查询所有预定订单
GET http://localhost:8081/ordering/selectAll
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

### update预定中间表订单
POST http://localhost:8081/ordering/update
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
    "orderCode": 1 ,
    "guestId" : 4
}


### update预定订单
POST http://localhost:8081/orderForm/update
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
  "orderCode": "14",
  "lastName": "龚",
  "gender": "先生",
  "orderTime": "2021-04-12T02:06:02.000+00:00",
  "phoneNumber": "13224011982",
  "guestNumber": "7",
  "guestId": "12",
  "orderStatus": "预定成功"
}

### 登录方法
POST http://localhost:8081/userLogin
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
  "id" : "1",
  "password" : "123"
}

### 获取所有table信息
GET http://localhost:8081/table/selectAll
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

### 排队数据测试
POST http://localhost:8081/queuingExcel/queuingNumber
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
    "dateId" : 1
}