### 根据id查询唯一预定订单
POST http://localhost:8081/ordering/selectOne
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
    "orderCode": 1
}

### 查询所有预定订单
POST http://localhost:8081/ordering/selectAll
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

### update预定订单
POST http://localhost:8081/ordering/update
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
    "orderCode": 1 ,
    "guestId" : 4
}

