server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.173.246:3306/queuingSys
    username: root
    password: a13098663096A
logging:
  level:
    org.springframework: info
mybatis:
  # mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.ahzeng.queuingSys.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl