server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.173.246:3306/queuingSys?characterEncoding=utf-8
    username: root
    password: a13098663096A
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /templates
      suffix: .html
logging:
  level:
    org.springframework: info
mybatis:
  # mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.ahzeng.queuingSys.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

